# Component parts
PARTS_FUSE_AC250V = body pins label

COLOR_FUSE_AC250V_body = 0.8 0.8 0.8
COLOR_FUSE_AC250V_pins = 0.6 0.6 0.6
COLOR_FUSE_AC250V_label = 0.0 0.0 0.0

$(eval $(call assemble,FUSE_AC250V))
