# Component parts
PARTS_SIM68M = pcb pins shield label pin1

COLOR_SIM68M_pcb = $(COLOR_PCB)
COLOR_SIM68M_pins = $(COLOR_PIN)
COLOR_SIM68M_shield = $(COLOR_SHIELD)
COLOR_SIM68M_label = $(COLOR_LABEL)
COLOR_SIM68M_pin1 = $(COLOR_RED_DOT)

$(eval $(call assemble,SIM68M))
