# Component parts
PARTS_GPS_35_35_4 = body pin silver

COLOR_GPS_35_35_4_body = 0.83 0.77 0.75
COLOR_GPS_35_35_4_pin = 0.9 0.9 0.9
COLOR_GPS_35_35_4_silver = 0.85 0.85 0.85

$(eval $(call assemble,GPS_35_35_4))
