# Component parts
PARTS_GPS_18_18_2 = body pin silver

COLOR_GPS_18_18_2_body = 0.83 0.77 0.75
COLOR_GPS_18_18_2_pin = 0.9 0.9 0.9
COLOR_GPS_18_18_2_silver = 0.85 0.85 0.85

$(eval $(call assemble,GPS_18_18_2))
