# Component parts
PARTS_SI37C_SIM_HOLDER = body pins cover

COLOR_SI37C_SIM_HOLDER_body = 0.4 0.4 0.4
COLOR_SI37C_SIM_HOLDER_pins = 0.7 0.7 0.7
COLOR_SI37C_SIM_HOLDER_cover = 0.7 0.7 0.7

$(eval $(call assemble,SI37C_SIM_HOLDER))
