# Component parts
PARTS_WQFN-30_6x6mm_P0.5mm = body label pins

COLOR_WQFN-30_6x6mm_P0.5mm_body = 0.2 0.2 0.2
COLOR_WQFN-30_6x6mm_P0.5mm_label = 0.8 0.8 0.8
COLOR_WQFN-30_6x6mm_P0.5mm_pins = $(COLOR_PIN)

$(eval $(call assemble,WQFN-30_6x6mm_P0.5mm))
