# Component parts
PARTS_RS-282G05A3 = body pins key

COLOR_RS-282G05A3_body = 0.7 0.7 0.7
COLOR_RS-282G05A3_pins = 0.7 0.7 0.7
COLOR_RS-282G05A3_key = 0.9 0.9 0.9

$(eval $(call assemble,RS-282G05A3))
