# Component parts
PARTS_HDC1080DM = body frame label pins

COLOR_HDC1080DM_body = 0.2 0.2 0.2
COLOR_HDC1080DM_label = 0.8 0.8 0.8
COLOR_HDC1080DM_frame = 1.0 0.6 0.0
COLOR_HDC1080DM_pins = $(COLOR_PIN)

$(eval $(call assemble,HDC1080DM))
