# Component parts
PARTS_FUSE_1812 = body pins paint label

COLOR_FUSE_1812_body = 0.2 0.2 0.2
COLOR_FUSE_1812_pins = 1.0 1.0 1.0
COLOR_FUSE_1812_paint = 0.0 0.6 0.0
COLOR_FUSE_1812_label = 0.8 0.8 0.8

$(eval $(call assemble,FUSE_1812))
