# Component parts
PARTS_SIM800C = pcb pins shield label pin1

COLOR_SIM800C_pcb = $(COLOR_PCB)
COLOR_SIM800C_pins = $(COLOR_PIN)
COLOR_SIM800C_shield = $(COLOR_SHIELD)
COLOR_SIM800C_label = $(COLOR_LABEL)
COLOR_SIM800C_pin1 = $(COLOR_RED_DOT)

$(eval $(call assemble,SIM800C))
