# Component parts
#PARTS_BQ5105XB = body label pins

#COLOR_BQ5105XB_body = 0.2 0.2 0.2
#COLOR_BQ5105XB_label = 0.8 0.8 0.8
#COLOR_BQ5105XB_pins = $(COLOR_PIN)

#$(eval $(call assemble,BQ5105XB))

$(BUILD_PATH)/CadTemplate.wrl: $(SRC_PATH)/CadTemplate/make.py
	echo "TBD $< to $@"
	python $< $@

#TARGETS += $(BUILD_PATH)/CadTemplate.wrl
#MODELS += CadTemplate
