# Component parts
PARTS_LED_LTST-S270TBKT = body pins label emitter

COLOR_LED_LTST-S270TBKT_body = 0.8 0.8 0.8
COLOR_LED_LTST-S270TBKT_pins = 1.0 0.83 0
COLOR_LED_LTST-S270TBKT_label = 0.2 1.0 0.2
COLOR_LED_LTST-S270TBKT_emitter = 0.2 0.2 1.0

$(eval $(call assemble,LED_LTST-S270TBKT))
